# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  # config.vm.boot_mode = :gui
  config.vm.customize ["modifyvm", :id, "--memory", 2048]
  config.vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

  config.vm.forward_port 80, 8000
  config.vm.forward_port 8080, 8080

  config.vm.share_folder "sawmill-dev", "/home/vagrant/sawmill", ".."
  # By default, virtualbox doesn't allow symlinks on shares
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/sawmill-dev", "1"]

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = [ "cookbooks", "~/.chef/cookbooks/" ]
    chef.add_recipe("apt")
    chef.add_recipe("sawmill::dev")
    chef.json = {}
  end
end
